
version: "3"
services:
  app:
    container_name: app
    restart: always
    build: ./backend
    ports:
      - "4000:4000"
  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - "4200:4200"
    links:
      - app